
# Multiple LLM configurations pool (model name is the unique key)
llms:
  - api_type: "openai"
    base_url: "https://api.siliconflow.cn/v1"
    model: "Qwen/Qwen3-8B"
    api_key: "${SILICONFLOW_API_KEY}"
  # - api_type: "openai"
  #   base_url: "https://cfcus02.opapi.win/v1"
  #   model: "TA/meta-llama/Llama-3-8b-chat-hf"
  #   api_key: "${OPAPI_API_KEY}"
  # - api_type: "openai"
  #   base_url: "https://cfcus02.opapi.win/v1"
  #   model: "gpt-4o-mini"
  #   api_key: "${OPAPI_API_KEY}"
  # - api_type: "openai"
  #   base_url: "https://cfcus02.opapi.win/v1"
  #   model: "gpt-4o"
  #   api_key: "${OPAPI_API_KEY}"


embedding:
  api_type: "modelscope"  # or  ollama / etc.
  base_url: "http://localhost:8007/v1"  # or forward url / other llm url
  api_key: "${EMBEDDING_API_KEY}"
  # api_key: "${EMBEDDING_API_KEY:-YOUR_API_KEY}"
  model: "Qwen3-Embedding-0.6B"
  cache_folder: ""
  dimensions: 1024
  max_token_size: 8102
  embed_batch_size: 128
  target_devices: ["cuda:4"]
  backend: "openai"
  embedding_func_max_async: 16
 
data_root: /mnt/data/wangshu/hcarag/ids_data # Root directory for data

working_dir: /mnt/data/yingli/RAGTuner/ # Result directory for the experiment
exp_name: tpebo # Experiment name
vdb_type: faiss
faiss_hnsw_m: 32
faiss_hnsw_ef_search: 64
faiss_hnsw_ef_construction: 40
faiss_metric: l2
# 
